#!/usr/bin/env python3
"""
Local server for the Hobby Progress Challenge tracker.

Serves the tracker from this folder and saves everything it records back into
this same folder, automatically:

    data.json          the plan, notes, statuses and backlog
    data.json.bak      data.json as it was when the server last started
    photos/            full-size photos
    photos/thumbs/     small previews used by the year board

It listens on 127.0.0.1 only, so nothing outside this PC can reach it, and it
uses the Python standard library only - nothing to install, nothing contacted.

Usage:  python server.py [--port 8787] [--no-browser]
"""

import argparse
import json
import mimetypes
import os
import re
import shutil
import socket
import sys
import threading
import time
import urllib.request
import webbrowser
from http import HTTPStatus
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import unquote, urlsplit

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data.json"
DATA_BAK = ROOT / "data.json.bak"
PHOTOS = ROOT / "photos"
APP_PAGE = "hobby-progress-challenge.html"
HOST = "127.0.0.1"
DEFAULT_PORT = 8787
MAX_BODY = 80 * 1024 * 1024  # a single photo larger than this is refused

# Photo names are generated by the app. Anything else is refused, which also
# rules out path tricks like "..\..\Windows".
BLOB_NAME = re.compile(r"^(thumbs/)?[A-Za-z0-9][A-Za-z0-9._-]{0,150}$")

write_lock = threading.Lock()


def atomic_write(path: Path, data: bytes) -> None:
    """Write via a temp file and swap it in, so a crash never leaves half a file.

    Retries briefly because OneDrive and antivirus scanners on Windows can hold
    a file open for a moment right after it changes.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    with open(tmp, "wb") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    for attempt in range(20):
        try:
            os.replace(tmp, path)
            return
        except PermissionError:
            if attempt == 19:
                raise
            time.sleep(0.05)


def blob_path(name: str):
    if not BLOB_NAME.match(name):
        return None
    path = (PHOTOS / name).resolve()
    return path if PHOTOS.resolve() in path.parents else None


class Handler(SimpleHTTPRequestHandler):
    server_version = "HPCTracker/1"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    # ---- plumbing ---------------------------------------------------------

    def log_request(self, code="-", size="-"):
        # Page loads and thumbnails are noise; show writes and failures.
        try:
            failed = int(code) >= 400
        except (TypeError, ValueError):
            failed = False
        if self.command != "GET" or failed:
            super().log_request(code, size)

    def _request_ok(self) -> bool:
        """Only answer requests addressed to this machine by a page on this machine.

        The Host check stops a web page elsewhere from reaching this server by
        pointing its own domain name at 127.0.0.1.
        """
        host = (self.headers.get("Host") or "").rsplit(":", 1)[0].lower()
        if host not in ("127.0.0.1", "localhost"):
            return False
        origin = self.headers.get("Origin")
        if origin and self.command not in ("GET", "HEAD"):
            if (urlsplit(origin).hostname or "").lower() not in ("127.0.0.1", "localhost"):
                return False
        return True

    def end_headers(self):
        # The page itself and anything else served as a plain file: make the
        # browser check for a newer copy on every load. Without this it may
        # quietly keep running an old version of the tracker after an update.
        # Unchanged files still come back as a quick "304 Not Modified".
        if not getattr(self, "_cache_header_sent", False):
            self.send_header("Cache-Control", "no-cache")
        self._cache_header_sent = False  # connections are reused across requests
        super().end_headers()

    def _send(self, status, body: bytes, content_type: str, cache="no-store"):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", cache)
        self._cache_header_sent = True
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def _json(self, status, payload):
        self._send(status, json.dumps(payload).encode("utf-8"), "application/json; charset=utf-8")

    def _api(self):
        path = urlsplit(self.path).path
        return unquote(path[len("/api/"):]) if path.startswith("/api/") else None

    def _body(self):
        """Read the upload. Always consume it before replying, even to refuse
        it: answering with bytes still unread makes Windows reset the
        connection, so the page sees a network error instead of the reason."""
        try:
            length = int(self.headers.get("Content-Length") or 0)
        except ValueError:
            length = 0
        if length > MAX_BODY:
            self.close_connection = True  # too big to be worth draining
            return None
        return self.rfile.read(length)

    # ---- verbs ------------------------------------------------------------

    def do_HEAD(self):
        if self._api() is not None:
            return self.do_GET()  # _send leaves the body out for HEAD
        if not self._request_ok():
            return self._json(HTTPStatus.FORBIDDEN, {"error": "forbidden"})
        super().do_HEAD()

    def do_GET(self):
        if not self._request_ok():
            return self._json(HTTPStatus.FORBIDDEN, {"error": "forbidden"})

        api = self._api()
        if api is None:
            if urlsplit(self.path).path == "/":
                self.send_response(HTTPStatus.FOUND)
                self.send_header("Location", "/" + APP_PAGE)
                self.end_headers()
                return
            return super().do_GET()

        if api == "ping":
            return self._json(200, {"ok": True, "app": "hpc-tracker",
                                    "root": str(ROOT), "photos": str(PHOTOS)})
        if api == "doc":
            if not DATA.exists():
                return self._json(200, None)
            return self._send(200, DATA.read_bytes(), "application/json; charset=utf-8")
        if api == "blobs":
            names = []
            if PHOTOS.exists():
                for p in PHOTOS.rglob("*"):
                    if p.is_file() and not p.name.endswith(".tmp"):
                        names.append(p.relative_to(PHOTOS).as_posix())
            return self._json(200, names)
        if api.startswith("blob/"):
            path = blob_path(api[len("blob/"):])
            if not path:
                return self._json(400, {"error": "bad photo name"})
            if not path.is_file():
                return self._json(404, {"error": "not found"})
            ctype = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
            # Names are unique per photo, so the browser may cache them for good.
            return self._send(200, path.read_bytes(), ctype, cache="private, max-age=31536000, immutable")

        return self._json(404, {"error": "unknown endpoint"})

    def do_PUT(self):
        body = self._body()
        if not self._request_ok():
            return self._json(HTTPStatus.FORBIDDEN, {"error": "forbidden"})
        if body is None:
            return self._json(413, {"error": "too large"})
        api = self._api()

        if api == "doc":
            try:
                json.loads(body)
            except ValueError:
                return self._json(400, {"error": "not valid JSON"})
            with write_lock:
                atomic_write(DATA, body)
            return self._json(200, {"ok": True})

        if api and api.startswith("blob/"):
            path = blob_path(api[len("blob/"):])
            if not path:
                return self._json(400, {"error": "bad photo name"})
            with write_lock:
                atomic_write(path, body)
            return self._json(200, {"ok": True})

        return self._json(404, {"error": "unknown endpoint"})

    def do_DELETE(self):
        self._body()
        if not self._request_ok():
            return self._json(HTTPStatus.FORBIDDEN, {"error": "forbidden"})
        api = self._api()
        if api and api.startswith("blob/"):
            path = blob_path(api[len("blob/"):])
            if not path:
                return self._json(400, {"error": "bad photo name"})
            with write_lock:
                path.unlink(missing_ok=True)
            return self._json(200, {"ok": True})
        return self._json(404, {"error": "unknown endpoint"})

    def do_POST(self):
        self._body()
        if not self._request_ok():
            return self._json(HTTPStatus.FORBIDDEN, {"error": "forbidden"})
        if self._api() == "open-folder":
            if hasattr(os, "startfile"):
                os.startfile(str(ROOT))  # opens File Explorer on this folder
                return self._json(200, {"ok": True})
            return self._json(501, {"error": "only supported on Windows"})
        return self._json(404, {"error": "unknown endpoint"})


def already_running(port: int) -> bool:
    """True if this same tracker is already being served on `port`."""
    try:
        with urllib.request.urlopen(f"http://{HOST}:{port}/api/ping", timeout=1) as r:
            info = json.load(r)
        return info.get("app") == "hpc-tracker" and Path(info.get("root", "")) == ROOT
    except Exception:
        return False


def free_port(preferred: int) -> int:
    for port in range(preferred, preferred + 20):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind((HOST, port))
                return port
            except OSError:
                continue
    sys.exit("Could not find a free port near %d." % preferred)


def main():
    parser = argparse.ArgumentParser(description="Run the Hobby Progress Challenge tracker.")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--no-browser", action="store_true", help="don't open a browser tab")
    args = parser.parse_args()

    # Two servers writing one data.json would trample each other, so if the
    # tracker is already up just bring its page forward instead.
    if already_running(args.port):
        url = f"http://{HOST}:{args.port}/{APP_PAGE}"
        print("The tracker is already running - opening", url)
        if not args.no_browser:
            webbrowser.open(url)
        return

    port = free_port(args.port)
    PHOTOS.mkdir(exist_ok=True)
    (PHOTOS / "thumbs").mkdir(exist_ok=True)
    if DATA.exists():
        shutil.copyfile(DATA, DATA_BAK)  # a way back if this session goes wrong

    server = ThreadingHTTPServer((HOST, port), Handler)
    url = f"http://{HOST}:{port}/{APP_PAGE}"
    print()
    print("  Hobby Progress Challenge tracker")
    print("  --------------------------------")
    print("  Open:    ", url)
    print("  Saving:  ", ROOT)
    print()
    print("  Keep this window open while you use the tracker.")
    print("  Close it, or press Ctrl+C, when you're done.")
    print()

    if not args.no_browser:
        threading.Timer(0.6, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
        print("  Stopped. Everything is saved in", ROOT)


if __name__ == "__main__":
    main()
